In [ ]:
import pandas as pd

df= pd.read_csv('data_no_mol_desc.tsv', sep = '\t')
df.head(100)

/tmp/ipykernel_18014/960470629.py:3: DtypeWarning: Columns (2,14) have mixed types. Specify dtype option on import or set low_memory=False.
  df= pd.read_csv('data_no_mol_desc.tsv', sep = '\t')

,id,molecule_id,name,formula,rt,smiles.std,inchi.std,inchikey.std,classyfire.kingdom,classyfire.superclass,...,B [%]_16,C [%]_16,D [%]_16,flow rate [ml/min]_16,t [min]_17,A [%]_17,B [%]_17,C [%]_17,D [%]_17,flow rate [ml/min]_17
0,1,0001_00001,epicatechin,C15H14O6,12.070,C1C(C(OC2=CC(=CC(=C21)O)O)C3=CC(=C(C=C3)O)O)O,InChI=1S/C15H14O6/c16-8-4-11(18)9-6-13(20)15(2...,PFTAWBLQPZVEMU-UHFFFAOYSA-N,Organic compounds (CHEMONTID:0000000),Phenylpropanoids and polyketides (CHEMONTID:00...,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1,0001_00002,epicatechin gallate,C22H18O10,15.990,C1C(C(OC2=CC(=CC(=C21)O)O)C3=CC(=C(C=C3)O)O)OC...,InChI=1S/C22H18O10/c23-11-6-14(25)12-8-19(32-2...,LSHVYAFMTMFKBA-UHFFFAOYSA-N,Organic compounds (CHEMONTID:0000000),Phenylpropanoids and polyketides (CHEMONTID:00...,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1,0001_00003,gallocatechin,C15H14O7,8.675,C1C(C(OC2=CC(=CC(=C21)O)O)C3=CC(=C(C(=C3)O)O)O)O,InChI=1S/C15H14O7/c16-7-3-9(17)8-5-12(20)15(22...,XMOCLSLCDHWDHP-UHFFFAOYSA-N,Organic compounds (CHEMONTID:0000000),Phenylpropanoids and polyketides (CHEMONTID:00...,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1,0001_00004,"3,5-dihydroxybenzoic acid",C7H6O4,7.750,C1=C(C=C(C=C1O)O)C(=O)O,InChI=1S/C7H6O4/c8-5-1-4(7(10)11)2-6(9)3-5/h1-...,UYEMGAFJOZZIFP-UHFFFAOYSA-N,Organic compounds (CHEMONTID:0000000),Benzenoids (CHEMONTID:0002448),...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1,0001_00005,4-hydroxybenzoic acid,C7H6O3,10.600,C1=CC(=CC=C1C(=O)O)O,"InChI=1S/C7H6O3/c8-6-3-1-5(2-4-6)7(9)10/h1-4,8...",FJKROLUGYXJWQN-UHFFFAOYSA-N,Organic compounds (CHEMONTID:0000000),Benzenoids (CHEMONTID:0002448),...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,2,0002_00020,isorhamnetin 3-glucoside,C22H22O12,31.530,COC1=C(C=CC(=C1)C2=C(C(=O)C3=C(C=C(C=C3O2)O)O)...,InChI=1S/C22H22O12/c1-31-12-4-8(2-3-10(12)25)2...,CQLRUIIRRZYHHS-UHFFFAOYSA-N,Organic compounds (CHEMONTID:0000000),Phenylpropanoids and polyketides (CHEMONTID:00...,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
96,2,0002_00021,isorhamnetin 3-rutinoside,C28H32O16,31.700,CC1C(C(C(C(O1)OCC2C(C(C(C(O2)OC3=C(OC4=CC(=CC(...,InChI=1S/C28H32O16/c1-9-18(32)21(35)23(37)27(4...,UIDGLYUNOUKLBM-UHFFFAOYSA-N,Organic compounds (CHEMONTID:0000000),Phenylpropanoids and polyketides (CHEMONTID:00...,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
97,2,0002_00022,isorhapontin,C21H24O9,26.130,COC1=C(C=CC(=C1)C=CC2=CC(=CC(=C2)OC3C(C(C(C(O3...,InChI=1S/C21H24O9/c1-28-16-8-11(4-5-15(16)24)2...,KLPUXMNQDCUPNO-UHFFFAOYSA-N,Organic compounds (CHEMONTID:0000000),Phenylpropanoids and polyketides (CHEMONTID:00...,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
98,2,0002_00023,kaempferol 3-glucoside,C21H20O11,31.250,C1=CC(=CC=C1C2=C(C(=O)C3=C(C=C(C=C3O2)O)O)OC4C...,InChI=1S/C21H20O11/c22-7-13-15(26)17(28)18(29)...,JPUKWEQWGBDDQB-UHFFFAOYSA-N,Organic compounds (CHEMONTID:0000000),Phenylpropanoids and polyketides (CHEMONTID:00...,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
99,2,0002_00024,kaempferol 3-rutinoside,C27H30O15,31.350,CC1C(C(C(C(O1)OCC2C(C(C(C(O2)OC3=C(OC4=CC(=CC(...,InChI=1S/C27H30O15/c1-9-17(31)20(34)22(36)26(3...,RTATXGUCZHCSNG-UHFFFAOYSA-N,Organic compounds (CHEMONTID:0000000),Phenylpropanoids and polyketides (CHEMONTID:00...,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
df.shape

(213098, 246)

In [ ]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [ ]:
df.dtypes

id                               int64
molecule_id                     object
name                            object
formula                         object
rt                             float64
smiles.std                      object
inchi.std                       object
inchikey.std                    object
classyfire.kingdom              object
classyfire.superclass           object
classyfire.class                object
classyfire.subclass             object
classyfire.level5               object
classyfire.level6               object
comment                         object
column.name                     object
column.usp.code_L1             float64
column.usp.code_L10            float64
column.usp.code_L109           float64
column.usp.code_L11            float64
column.usp.code_L114           float64
column.usp.code_L122           float64
column.usp.code_L3             float64
column.usp.code_L43            float64
column.usp.code_L68            float64
column.usp.code_L7             float64
column.usp.code_nan            float64
column.usp.code                 object
column.length                  float64
column.id                      float64
column.particle.size           float64
column.temperature             float64
column.flowrate                float64
column.t0                      float64
eluent.A.h2o                   float64
eluent.A.meoh                    int64
eluent.A.acn                     int64
eluent.A.iproh                   int64
eluent.A.acetone               float64
eluent.A.hex                     int64
eluent.A.chcl3                   int64
eluent.A.ch2cl2                  int64
eluent.A.hept                    int64
eluent.A.formic                float64
eluent.A.acetic                float64
eluent.A.trifluoroacetic       float64
eluent.A.phosphor              float64
eluent.A.nh4ac                 float64
eluent.A.nh4form               float64
eluent.A.nh4carb               float64
eluent.A.nh4bicarb             float64
eluent.A.nh4f                  float64
eluent.A.nh4oh                 float64
eluent.A.trieth                  int64
eluent.A.triprop                 int64
eluent.A.tribut                float64
eluent.A.nndimethylhex           int64
eluent.A.medronic              float64
eluent.A.pH                    float64
eluent.A.heptafluorobutyric    float64
eluent.B.h2o                     int64
eluent.B.meoh                  float64
eluent.B.acn                     int64
eluent.B.iproh                   int64
eluent.B.acetone               float64
eluent.B.hex                     int64
eluent.B.chcl3                   int64
eluent.B.ch2cl2                  int64
eluent.B.hept                    int64
eluent.B.formic                float64
eluent.B.acetic                float64
eluent.B.trifluoroacetic       float64
eluent.B.phosphor                int64
eluent.B.nh4ac                 float64
eluent.B.nh4form               float64
eluent.B.nh4carb               float64
eluent.B.nh4bicarb             float64
eluent.B.nh4f                  float64
eluent.B.nh4oh                 float64
eluent.B.trieth                  int64
eluent.B.triprop                 int64
eluent.B.tribut                float64
eluent.B.nndimethylhex           int64
eluent.B.medronic              float64
eluent.B.pH                    float64
eluent.B.heptafluorobutyric    float64
eluent.C.h2o                     int64
eluent.C.meoh                    int64
eluent.C.acn                     int64
eluent.C.iproh                   int64
eluent.C.acetone               float64
eluent.C.hex                     int64
eluent.C.chcl3                   int64
eluent.C.ch2cl2                  int64
eluent.C.hept                    int64
eluent.C.formic                  int64
eluent.C.acetic                  int64
eluent.C.trifluoroacetic         int64
eluent.C.phosphor                int64
eluent.C.nh4ac                   int64
eluent.C.nh4form                 int64
eluent.C.nh4carb                 int64
eluent.C.nh4bicarb               int64
eluent.C.nh4f                    int64
eluent.C.nh4oh                   int64
eluent.C.trieth                  int64
eluent.C.triprop                 int64
eluent.C.tribut                  int64
eluent.C.nndimethylhex           int64
eluent.C.medronic                int64
eluent.C.pH                    float64
eluent.C.heptafluorobutyric    float64
eluent.D.h2o                     int64
eluent.D.meoh                    int64
eluent.D.acn                     int64
eluent.D.iproh                   int64
eluent.D.acetone               float64
eluent.D.hex                     int64
eluent.D.chcl3                   int64
eluent.D.ch2cl2                  int64
eluent.D.hept                    int64
eluent.D.formic                  int64
eluent.D.acetic                  int64
eluent.D.trifluoroacetic         int64
eluent.D.phosphor                int64
eluent.D.nh4ac                   int64
eluent.D.nh4form                 int64
eluent.D.nh4carb                 int64
eluent.D.nh4bicarb               int64
eluent.D.nh4f                    int64
eluent.D.nh4oh                   int64
eluent.D.trieth                  int64
eluent.D.triprop                 int64
eluent.D.tribut                  int64
eluent.D.nndimethylhex           int64
eluent.D.medronic                int64
eluent.D.pH                    float64
eluent.D.heptafluorobutyric    float64
t [min]_0                      float64
A [%]_0                        float64
B [%]_0                        float64
C [%]_0                        float64
D [%]_0                        float64
flow rate [ml/min]_0           float64
t [min]_1                      float64
A [%]_1                        float64
B [%]_1                        float64
C [%]_1                        float64
D [%]_1                        float64
flow rate [ml/min]_1           float64
t [min]_2                      float64
A [%]_2                        float64
B [%]_2                        float64
C [%]_2                        float64
D [%]_2                        float64
flow rate [ml/min]_2           float64
t [min]_3                      float64
A [%]_3                        float64
B [%]_3                        float64
C [%]_3                        float64
D [%]_3                        float64
flow rate [ml/min]_3           float64
t [min]_4                      float64
A [%]_4                        float64
B [%]_4                        float64
C [%]_4                        float64
D [%]_4                        float64
flow rate [ml/min]_4           float64
t [min]_5                      float64
A [%]_5                        float64
B [%]_5                        float64
C [%]_5                        float64
D [%]_5                        float64
flow rate [ml/min]_5           float64
t [min]_6                      float64
A [%]_6                        float64
B [%]_6                        float64
C [%]_6                        float64
D [%]_6                        float64
flow rate [ml/min]_6           float64
t [min]_7                      float64
A [%]_7                        float64
B [%]_7                        float64
C [%]_7                        float64
D [%]_7                        float64
flow rate [ml/min]_7           float64
t [min]_8                      float64
A [%]_8                        float64
B [%]_8                        float64
C [%]_8                        float64
D [%]_8                        float64
flow rate [ml/min]_8           float64
t [min]_9                      float64
A [%]_9                        float64
B [%]_9                        float64
C [%]_9                        float64
D [%]_9                        float64
flow rate [ml/min]_9           float64
t [min]_10                     float64
A [%]_10                       float64
B [%]_10                       float64
C [%]_10                       float64
D [%]_10                       float64
flow rate [ml/min]_10          float64
t [min]_11                     float64
A [%]_11                       float64
B [%]_11                       float64
C [%]_11                       float64
D [%]_11                       float64
flow rate [ml/min]_11          float64
t [min]_12                     float64
A [%]_12                       float64
B [%]_12                       float64
C [%]_12                       float64
D [%]_12                       float64
flow rate [ml/min]_12          float64
t [min]_13                     float64
A [%]_13                       float64
B [%]_13                       float64
C [%]_13                       float64
D [%]_13                       float64
flow rate [ml/min]_13          float64
t [min]_14                     float64
A [%]_14                       float64
B [%]_14                       float64
C [%]_14                       float64
D [%]_14                       float64
flow rate [ml/min]_14          float64
t [min]_15                     float64
A [%]_15                       float64
B [%]_15                       float64
C [%]_15                       float64
D [%]_15                       float64
flow rate [ml/min]_15          float64
t [min]_16                     float64
A [%]_16                       float64
B [%]_16                       float64
C [%]_16                       float64
D [%]_16                       float64
flow rate [ml/min]_16          float64
t [min]_17                     float64
A [%]_17                       float64
B [%]_17                       float64
C [%]_17                       float64
D [%]_17                       float64
flow rate [ml/min]_17          float64
dtype: object

In [ ]:
df["column.name"].nunique()

57

In [ ]:
df["column.name"].value_counts()

column.name
Agilent ZORBAX Extend-C18                                 83738
Waters ACQUITY UPLC BEH C18                               42787
Merck Supelco Ascentis Express C18                        12464
Thermo Scientific Acclaim RSLC 120 C18                     7913
Waters ACQUITY UPLC HSS C18                                7127
Restek Raptor Biphenyl                                     6915
Waters ACQUITY UPLC HSS T3                                 6750
Waters CORTECS UPLC C18                                    6674
Waters CORTECS T3                                          4943
Phenomenex Kinetex XB-C18                                  4502
Waters ACQUITY UPLC BEH Amide                              3290
Phenomenex Kinetex C18                                     2333
Merck SeQuant ZIC-HILIC                                    2235
Agilent ZORBAX 300 SB-C18                                  2194
Thermo Scientific Hypersil GOLD                            1270
Waters XBridge BEH Amide                                   1220
Thermo Scientific Accucore HILIC                           1206
Phenomenex Kinetex PS C18                                  1183
Waters ACQUITY Premier BEH C18                             1100
Agilent ZORBAX Eclipse Plus C18                            1086
Waters XSelect HSS T3 XP                                   1027
Merck SeQuant ZIC-pHILIC                                    981
Phenomenex Kinetex EVO C18                                  934
Phenomenex Synergi Polar-RP                                 870
HILICON iHILIC-(P) Classic, HILIC, PEEK                     825
Waters SunFire C18                                          689
Waters Atlantis Premier BEH Z-HILIC                         579
Waters XBridge C18                                          472
Thermo Scientific Accucore C18                              377
Waters ACQUITY Premier HSS T3                               363
Merck Supelco Ascentis Express F5 (PFP)                     359
Waters ACQUITY UPLC BEH C8                                  357
Waters Atlantis T3                                          345
Merck Supelco Ascentis Express ES-Cyano                     345
Merck Supelco Ascentis Express Phenyl-Hexyl                 340
Thermo Scientific Hypersil GOLD aQ                          304
Waters ACQUITY UPLC BEH Shield RP18                         267
Agilent ZORBAX Eclipse XDB-C18                              211
Agilent ZORBAX RRHD Eclipse Plus C18                        205
Waters ACQUITY UPLC BEH HILIC                               198
Agilent InfinityLab Poroshell 120 EC-C18                    177
Phenomenex Kinetex HILIC                                    167
Thermo Scientific Hypercarb                                 162
Phenomenex Synergi Hydro-RP                                 156
Agilent InfinityLab Poroshell 120 SB-C18                    121
GL Sciences Inertsil ODS-4                                  119
Phenomenex Kinetex PFP                                      112
Phenomenex Luna Omega Polar C18                             103
Agilent InfinityLab Poroshell 120 HILIC-Z (Peek-lined)       98
Agilent ZORBAX Eclipse XDB-C8                                92
Waters XBridge BEH C18                                       78
Merck Supelco SUPELCOSIL LC-C18                              71
Merck LiChrospher RP-18                                      69
Waters Symmetry C18                                          65
Phenomenex Luna C18                                          57
Thermo Scientific Syncronis C18                              47
Hichrom Alltima HP C18                                       32
Name: count, dtype: int64

In [ ]:
df["column.usp.code"].nunique(dropna=False)

11

In [ ]:
df["column.usp.code"].value_counts(dropna=False)

column.usp.code
L1      192353
L11       8125
L68       4510
L122      2385
L114      2333
L3        1571
L43        471
L7         449
NaN        394
L10        345
L109       162
Name: count, dtype: int64

In [ ]:
datos_columna = df[[
    "id",
    "molecule_id",
    "rt",
    "column.name",
    "column.usp.code",
    "column.length",
    "column.id",
    "column.particle.size",
    "column.temperature",
    "column.flowrate",
    "column.t0"
]].copy()

In [ ]:
datos_columna.head(20)

,id,molecule_id,rt,column.name,column.usp.code,column.length,column.id,column.particle.size,column.temperature,column.flowrate,column.t0
0,1,0001_00001,12.070,Waters ACQUITY UPLC HSS T3,L1,150.0,2.1,1.8,40.0,0.28,1.18125
1,1,0001_00002,15.990,Waters ACQUITY UPLC HSS T3,L1,150.0,2.1,1.8,40.0,0.28,1.18125
2,1,0001_00003,8.675,Waters ACQUITY UPLC HSS T3,L1,150.0,2.1,1.8,40.0,0.28,1.18125
3,1,0001_00004,7.750,Waters ACQUITY UPLC HSS T3,L1,150.0,2.1,1.8,40.0,0.28,1.18125
4,1,0001_00005,10.600,Waters ACQUITY UPLC HSS T3,L1,150.0,2.1,1.8,40.0,0.28,1.18125
5,1,0001_00006,14.200,Waters ACQUITY UPLC HSS T3,L1,150.0,2.1,1.8,40.0,0.28,1.18125
6,1,0001_00007,8.530,Waters ACQUITY UPLC HSS T3,L1,150.0,2.1,1.8,40.0,0.28,1.18125
7,1,0001_00008,18.420,Waters ACQUITY UPLC HSS T3,L1,150.0,2.1,1.8,40.0,0.28,1.18125
8,1,0001_00009,20.370,Waters ACQUITY UPLC HSS T3,L1,150.0,2.1,1.8,40.0,0.28,1.18125
9,1,0001_00010,20.340,Waters ACQUITY UPLC HSS T3,L1,150.0,2.1,1.8,40.0,0.28,1.18125
10,1,0001_00011,15.550,Waters ACQUITY UPLC HSS T3,L1,150.0,2.1,1.8,40.0,0.28,1.18125
11,1,0001_00012,12.190,Waters ACQUITY UPLC HSS T3,L1,150.0,2.1,1.8,40.0,0.28,1.18125
12,1,0001_00013,11.840,Waters ACQUITY UPLC HSS T3,L1,150.0,2.1,1.8,40.0,0.28,1.18125
13,1,0001_00014,12.600,Waters ACQUITY UPLC HSS T3,L1,150.0,2.1,1.8,40.0,0.28,1.18125
14,1,0001_00015,21.130,Waters ACQUITY UPLC HSS T3,L1,150.0,2.1,1.8,40.0,0.28,1.18125
15,1,0001_00016,20.530,Waters ACQUITY UPLC HSS T3,L1,150.0,2.1,1.8,40.0,0.28,1.18125
16,1,0001_00017,20.590,Waters ACQUITY UPLC HSS T3,L1,150.0,2.1,1.8,40.0,0.28,1.18125
17,1,0001_00018,17.610,Waters ACQUITY UPLC HSS T3,L1,150.0,2.1,1.8,40.0,0.28,1.18125
18,1,0001_00019,20.285,Waters ACQUITY UPLC HSS T3,L1,150.0,2.1,1.8,40.0,0.28,1.18125
19,1,0001_00020,20.490,Waters ACQUITY UPLC HSS T3,L1,150.0,2.1,1.8,40.0,0.28,1.18125

In [ ]:
datos_columna.shape

(213098, 11)

In [ ]:
datos_columna.to_csv("datos_Columna.tsv", sep="\t", index=False)

In [ ]:
from google.colab import files
files.download("datos_Columna.tsv")